### ISSUE TITLE
Default URLMaps should be read-only

### ISSUE THREAD

**Issue by Aviv-Galmidi** [curiefense/curiefense#128]
In Policies&Rules page we have a document type called URL Maps. The default URL Map should be read only and only copyable instead of editable as it is the default fallback map to use when no other match is found

**Comment by spiros-reblaze** [comment]
If the default URL Map is not editable, then why is it there? What is it for?

It can't be for supplying defaults for the entire site/domain, because users will have different needs. We can't supply a default configuration that everyone will want.

(Should there be a default global Rate Limit? If so, what should its parameters be? Should the default WAF Policy be in Active Mode or not? What about the default ACL Policy? etc.)

And even individual users will have changing needs (e.g., enabling or disabling Active Mode for a WAF or ACL Policy). A read-only default configuration will be wrong for them, for at least part of the time.

So, most users will be forced to manually create a global default configuration that is appropriate for their needs.

But, since they can't edit the URL Map for the global path, they will have to manually create a separate URL Map for every subpath across the entire site/domain, for every site/domain that they have. 

And then, when they want to make a global change (e.g., moving an entire site/domain from report mode into Active mode, or setting a global rate limit, etc.), they will have to manually edit all of these various URL maps.

**This would be an extremely frustrating UX**. If users cannot edit the default URL Map, they will wonder:

"If I have to manually create URL Maps for subpaths anyway, why even bother having a global default? All it does is show me that there would be a much easier way to accomplish this task, but that I'm not allowed to have it."

**Comment by Aviv-Galmidi** [comment]
From my understanding, the logic behind making the default map read only is that it is the fallback for any request not matching any other url map. I am unsure on what we do right now if the default url map is missing or changed

This feature was requested by @tzuryby somewhat offhand during a meeting (something along the lines "we should make it read only" and then we moved on), so I might not have fully understood what he wanted to be done here. Might have been just so the default domain and default regex match `/` should be read only and everything else is editable?

Perhpas @tzuryby or @xavier-rbz can shine some more light on the subject

**Comment by spiros-reblaze** [comment]
> Might have been just so the default domain and default regex match `/` should be read only and everything else is editable?

Yes, this would be good. The UI already prevents the user from deleting the default entry; so, if the domain and regex match were read-only, there would always be a fallback, while still allowing users to easily control their global policies.
