### ISSUE TITLE
Conflicting URL Maps should be prevented

### ISSUE THREAD

**Issue by spiros-reblaze** [curiefense/curiefense#135]
A user can create multiple URL Maps for the same path, but this should not be allowed.

Currently, a user can duplicate an existing URL Map, and edit the new Map to have a different WAF Policy or ACL Policy than the original. This creates two conflicting URL Maps for the same path.

This problem is probably the most severe when it occurs for the default path, but this situation should be prevented in general. When a user attempts to save a newly edited/created URL Map, the system should verify that it does not conflict with an existing one.

**Comment by Aviv-Galmidi** [comment]
The default URL Map should be uneditable and relates to the following PR: https://github.com/curiefense/curiefense/issues/128

Other than that I'd like some clarification on what is considered a conflict. Does having the same domain name and map entry regex match considered a conflict? What about different matches that catch the same path, for example `foo` and `foo=50` would both match for `foo=50`

In addition, need to take into consideration the creation of new URL Maps as they take default values and thus may conflict, might need to change that to generate values that would not conflict

**Comment by spiros-reblaze** [comment]
> The default URL Map should be uneditable and relates to the following PR: #128

I added a comment to PR #128; I don't think the default URL Map should be read-only.

> Does having the same domain name and map entry regex match considered a conflict? What about different matches that catch the same path, for example `foo` and `foo=50` would both match for `foo=50`

Yes to both. However, it would be challenging to catch all possible conflicts. IMO we can leave some of this to the user; see below.

> need to take into consideration the creation of new URL Maps as they take default values and thus may conflict, might need to change that to generate values that would not conflict

I think that at minimum, the system should do two things:

-- Prevent a user from saving a URL Map with a combination of domain and Match value that already exists. (This would catch many, perhaps even most, of the possible errors. It would be better than generating new values during a duplication, because the user could still edit the new values and accidentally create a conflict again.)

-- Warn the user that if they define two URL Maps that could potentially match the same path, the resulting behavior is undefined; the user cannot predict which URL Map the system will use for that path. 

By warning the user, we can let them ensure that they are setting up their site/domain correctly. 

The warning should appear in two places:

-- The tooltip that appears when the cursor hovers over the "Match" field. Currently, this only says "Match"; ideally it would say something like, "A unique matching value, not overlapping other URL Map path definitions. See documentation for details."

-- Then the documentation could explain this situation in more detail.

**Comment by Aviv-Galmidi** [comment]
Regarding default URL map I'll continue the conversation on the other thread


> -- Prevent a user from saving a URL Map with a combination of domain and Match value that already exists. (This would catch many, perhaps even most, of the possible errors.

Understood

> It would be better than generating new values during a duplication, because the user could still edit the new values and accidentally create a conflict again.)

That's not what I meant when I was talking about generation of values. Right now when you create a new URL map the domain name and first entry regex match are pre-defined with default values, we would need to generate those so that the "new" button will not create conflicts (e.g. when you click the button to create a new url map, the domain name can't be `__default__` with a map entry regex `/` every time)

Same goes for the "Duplicate document" button, we would need to copy the inforamtion from the current URL map but change it somehow (perhaps the matching domain name) so that it would not conflict on creation


Regarding the warnings. I'm not a fan of sending the user to the documentations unless absolutely required, the UI should be as much self explanatory as possible. I can't think of an alternative at the moment as this is somewhat complicated so I won't object to elaborating in the documentation, just sharing my thoughts
