### ISSUE TITLE
"curieconfctl sync export" should request the server to export to the bucket

### ISSUE THREAD

**Issue by xavier-rbz** [curiefense/curiefense#48]
`curieconfctl sync export` tries to export to the bucket locally, rather than asking the server to do so. This breaks when using docker-compose, where by default the bucket is mounted to /bucket, which does not exist on the host.

See https://github.com/curiefense/curiefense/blob/master/curiefense/curieconf/client/curieconf/cli/__init__.py#L346

-> call the export API instead of calling the cloudstorage API

**Comment by flaper87** [comment]
Maybe I'm missing something here but it seems to me that the export command is doing the right thing: 

https://github.com/curiefense/curiefense/blob/0ecb1e01b882af5af54010d3483f94d44cb0ab53/curiefense/curieconf/client/curieconf/cli/__init__.py#L343-L346

It downloads the conf from the server L345 and then exports that conf to the destination bucket, which in the case of a local path is `file:///bucket/....`  

Isn't this the expected behavior? According to the docstring it looks like it is.

That said, it does fail if the local bucket directory doesn't exist, I've created the `/bucket` dir manually and that seems to have solved the issue with the export when using `file://`. After running the command, I see the conf files in the bucket dir

![DeepinScreenshot_select-area_20210220061302](https://user-images.githubusercontent.com/13816/108585861-b5cbcc00-7342-11eb-9bd9-e245353f350d.png)

**Comment by xavier-rbz** [comment]
It is indeed doing what it says it does: the client obtains the configuration from the server, then exports it. If the cloud bucket is an s3 bucket, then the client will write there (fails if the client doesn't have credentials); if it is a local path, then the client will write there (fails if the local path does not exist).

What I suggest is that the "writing to cloud storage" part be done by the *server* rather than the client. That is, `curieconfctl` would request the server to export a config to a cloud bucket. The client would not write anything to the bucket: that would be done by the server.

**Comment by flaper87** [comment]
A-ha, thanks! Now I understand what you meant.

What do you think should be the right behavior when asking to export using local path? Should the server still export to a local path mounted in the server? 

If I understand correctly the goal of the `export` command in this context, I'd say that the config should be exported locally (where curieconfctl is running). 

Another option I was considering is to add a flag `--local` to the export command which indicates that the export has to be done by curieconfctl.  If not passed, then the export will be done by the `confserver`. We can use the latter as the default behavior.

Thoughts?

**Comment by flaper87** [comment]
Alright, I looked at this in more detail. We already have a function/command to export configs remotely and it's publish. 

After looking at the API, the CLI implementation, and `curieconf.utils` it looks like it does exactly what we want. However, using `export` as the command name is confusing. Not sure how many tools are depending on it but we could plan on renaming it.

Am I missing something?

**Comment by xavier-rbz** [comment]
Indeed, `tool publish` does exactly what I needed. Thank you! #176 will fix this.
