### ISSUE TITLE
Include should be triggered before exclude in all components

### ISSUE THREAD

**Issue by yanushg** [curiefense/curiefense#505]
**Describe the bug**
Include should be triggered before exclude in all components
**To Reproduce**
1. Create a list with tag "test" and header "foo:bar" - save
2. Create another list with tag "yana" and header "foo:bar" - save 
3. Add one tag into include and another into exclude option in Flow control 
4. save and publish 
5. Send a request adding the header "foo:bar" - we should get blocked (we get 200 ) 
**Expected behavior**
We should get blocked by flow control 

Flow control conf:
{"id": "c03dabe4b9ca", "name": "Flow Control Example", "ttl": 60, "key": [{"attrs": "ip"}], "sequence": [{"method": "POST", "uri": "/login", "cookies": {}, "headers": {"host": "35.234.114.192:30081"}, "args": {}}, {"method": "GET", "uri": "/login", "cookies": {}, "headers": {"host": "35.234.114.192:30081"}, "args": {}}], "action": {"type": "default"}, "include": ["yana"], "exclude": ["test"], "notes": "New Flow Control Notes and Remarks", "active": true}

**Comment by bartavelle** [comment]
On the lua code, exclude is checked before include in rate limiting: https://github.com/curiefense/curiefense/blob/3bd8a98d8288fc26b4433aecde09c06398808bc8/curiefense/curieproxy/lua/limit.lua#L200-L202

In the dev branch, this is the same for flow control : https://github.com/curiefense/curiefense/blob/tzuryrust/curiefense/curieproxy/lua/flow.lua#L122-L123

Should I change the logic? Right now it is quite elegant because empty include/exclude is not special cased. What should be the logic on the following situations?

 * empty include selector, empty exclude selector, do not process this flow?
 * empty include selector, things in the exclude selector, do not process if anything match in exclude ?
 * things in the include selector, empty exclude selector, process only if all the things in the include selector match?
 * things in both selectors, process if all the things match the include selector, and ignore the exclude selector?

(also note that this code is moving out because of #462

**Comment by bartavelle** [comment]
It is a bit different than with tags, because tag selection required only one tag to match, while the Lua logic requires that all include criteria are matched (or that there are none) for it to pass.

**Comment by yanushg** [comment]
I saw the code and even the previous lua code 
Lets address to @tzuryby 
@tzuryby should we change the logic? Or it was intentional that the exclude is checked before?

**Comment by bartavelle** [comment]
@tzuryby more specifically:

 * when using selectors, what should be the order of preference, behavior when no element is matched, at least one, all elements, for both include and exclude, and when the include/exclude list is empty
 * when using tags, what should be the behavior when no tag, at least one tag, match, and when the include/exclude list is empty

**Comment by tzuryby** [comment]
The way it is!
Exclude and only the include.

@yanushg, generally speaking, when you have an opinion about a given design, file is as an idea for improvment, and not a bug.
